export enum BroadcastEnum {
  READY = "ready",
  DOWN = "down",
  RESTART = "restart",
  DISCONNECT = "disconnect",
}

export enum CommandEnum {
  CUM = "cum",
  P = "p",
  S = "s",
  SKIP = "skip",
  FIRST = "first",
  PL = "pl",
  SHUFFLE = "shuffle",
  R = "r",
  PAUSE = "pause",
  RESUME = "resume",
  NOW = "now",
  STOP = "stop",
  Q = "q",
  KILL = "kill",
  LEAVE = "leave",
  CREATE = "create",
  ADD = "add",
  TRUST = "trust",
  LISTALL = "listall",
  LIST = "list",
  DELSONG = "delsong",
  DELLIST = "dellist",
  LEAGUE = "league",
  CHAMP = "champ",
  PET = "pet",
  COMMANDS = "commands",
}
